spring:
  spring:
    output:
      ansi:
        enabled=always:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:test
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: on
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE